### ISSUE TITLE
Never thrown exception declared in method signature

### ISSUE THREAD

**Issue by lucas-giaco** [opendxl/opendxl-databus-client-java#26]
The [close](https://github.com/opendxl/opendxl-databus-client-java/blob/master/src/main/java/com/opendxl/databus/consumer/Consumer.java#L1204) method for the Consumer class stands that could throw an IOException which is impossible as you're making `catch Exception`

This is really annoying as we have to handle an exception that will never be thrown

**Comment by hvillalb** [comment]
> The [close](https://github.com/opendxl/opendxl-databus-client-java/blob/master/src/main/java/com/opendxl/databus/consumer/Consumer.java#L1204) method for the Consumer class stands that could throw an IOException which is impossible as you're making `catch Exception`
> 
> This is really annoying as we have to handle an exception that will never be thrown

Yes, you right. We will fix in the next version. In the meantime you can use:  
[public void close(Duration timeout)](https://github.com/opendxl/opendxl-databus-client-java/blob/16321f2652b35c096d147b3210c3dbe66250b549/src/main/java/com/opendxl/databus/consumer/Consumer.java#L1226)

**Comment by hvillalb** [comment]
Fixed in [2.4.1](https://github.com/opendxl/opendxl-databus-client-java/releases/tag/2.4.1)  release
